### ISSUE TITLE
Failed to start NGINX

### ISSUE THREAD

**Issue by dpadron** [techwise-technologies/tsuki-digital#1]
Greetings,
I have done the installation and I get an error starting NGINX. 

docker logs 
Web_Server    | nginx: [emerg] unknown directive "fastcgi_cache_purge" in /etc/nginx/conf.d/wordpress.conf:72

Thanks for your attention

**Comment by techwise-technologies** [comment]
thanks for the update, it is because the nginx conf has a conditional purge option but the nginx version is missing the cache purge module. we are working on adding conditional purging, for now i will comment out the conditional purge option and that should fix it.

**Comment by techwise-technologies** [comment]
it is done, u can try it now. it will work. we will upgrade nginx to add a dynamic module with conditional purge and update the source code.

**Comment by dpadron** [comment]
Thanks for your reply

**Comment by techwise-technologies** [comment]
source has been edited to include conditional purge, please feel free to test :)
