### ISSUE TITLE
Failed to start NGINX and build ProtonMail

### ISSUE THREAD

**Issue by dpadron** [techwise-technologies/tsuki-digital#2]
Hello there,
Performed a first installation and the following error appears:

go: finding github.com/emersion/go-smtp v0.14.0
# github.com/ProtonMail/proton-bridge/pkg/pmapi
pkg/pmapi/messages.go:339:24: signature.Hash.String undefined (type "crypto".Hash has no field or method String)
note: module requires Go 1.15
make: *** [Makefile:89: build-nogui] Error 2
The command '/bin/sh -c bash build.sh' returned a non-zero code: 2
ERROR: Service 'protonmail' failed to build : Build failed

Editing the proton-bridge / VERSION file and placing version 1.8.3, if it allows to continue the installation.

A second error is the following:

docker logs 
nginx: [emerg] unknown directive "fastcgi_cache_purge" in /etc/nginx/conf.d/wordpress.conf:72

The nginx container does not start

Thank you for your time

**Comment by techwise-technologies** [comment]
thank you for the report, 

1) Golang has been updated in the build base image to 1.15 and the mail server build is passing.

2) The nginx error is unusual, it builds successfully with conditional purging if the cache purge option is commented out in ~/nginx/conf.d/wordpress.conf and then re-enabled after deployment. It builds but fails to launch if the options are left 'on' in the config file.

I will look into why it does this, for now i will edit the deployment manual to work around this issue.

**Comment by techwise-technologies** [comment]
after running a few tests, it appears the conditional purging works from the UI without the configs specifically requiring it as the web server is compiled with custom dynamic modules.

the source code has been edited and deployment should work now.

thanks for your time.

**Comment by dpadron** [comment]
Excellent, everything seems to be working properly. I appreciate the work they do. Thank you so much

**Comment by techwise-technologies** [comment]
glad to hear :) thanks for the feedback
